{"uri":"file:///Users/vega/Code/huli/manager-web/src/vendor/aws/aws-sdk-php/src/Aws/CognitoSync/Exception/CognitoSyncException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Aws\\CognitoSync\\Exception","location":[2,0,2,36]},{"kind":1,"name":"ServiceResponseException","modifiers":4096,"location":[4,4,4,49],"associated":[{"kind":1,"name":"Aws\\Common\\Exception\\ServiceResponseException"}]},{"kind":1,"name":"Aws\\CognitoSync\\Exception\\CognitoSyncException","location":[9,0,9,62],"associated":[{"kind":1,"name":"Aws\\Common\\Exception\\ServiceResponseException"}],"description":"Exception thrown by the CognitoSync service client."}]}}