{"uri":"file:///Users/vega/Code/huli/manager-web/src/vendor/aws/aws-sdk-php/src/Aws/CloudTrail/Exception/InternalErrorException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Aws\\CloudTrail\\Exception","location":[16,0,16,35]},{"kind":1,"name":"Aws\\CloudTrail\\Exception\\InternalErrorException","location":[21,0,21,59],"associated":[{"kind":1,"name":"Aws\\CloudTrail\\Exception\\CloudTrailException"}],"description":"Exception that occurs when a InternalErrorException error is encountered"}]}}