{"uri":"file:///Users/vega/Code/huli/manager-web/src/vendor/aws/aws-sdk-php/src/Aws/CloudWatch/Exception/InternalServiceException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Aws\\CloudWatch\\Exception","location":[16,0,16,35]},{"kind":1,"name":"Aws\\CloudWatch\\Exception\\InternalServiceException","location":[21,0,21,61],"associated":[{"kind":1,"name":"Aws\\CloudWatch\\Exception\\CloudWatchException"}],"description":"Indicates that the request processing has failed due to some unknown error, exception, or failure."}]}}